# default configuration for waqfs/apple-music-rpc
[discord]
ping_interval_seconds = 15
reconnect_interval_seconds = 5

[activity]

[apple_music]
artwork_resolution = 512
timeout_seconds = 5
query_results_limit = 20
